### ISSUE TITLE
RuntimeError: running_mean should contain 256 elements not 512

### ISSUE THREAD

**Issue by zyzisastudyreallyhardguy** [Namkyeong/BGRL_Pytorch#1]
Dear BGRL authors, 

I try to run your open source code, but encounter RuntimeError: running_mean should contain 256 elements, not 512.

Could you please check the code and see why this issue happened?

Best!

**Comment by Namkyeong** [comment]
Hello
Thanks for pointing out our code error.

We fixed the error. 
It seems like batch normalization's dimension was inappropriate.

Best, Namkyeong

p.s. Actually I'm not authors of BGRL. I just read the paper and implemented since the official code was not available until now.
